# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ambito', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="Slug público tipo 'tercera-division' usado en la URL", max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="Slug público tipo 'grupo-xv' usado en la URL dentro de cada competición", max_length=120, null=True)),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='nucleo.competicion')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='nucleo.temporada')),
            ],
            options={
                'unique_together': {('competicion', 'temporada', 'slug')},
            },
        ),
    ]
