# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apodo', models.CharField(blank=True, max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('posicion_principal', models.CharField(blank=True, choices=[('portero', 'Portero'), ('cierre', 'Cierre'), ('ala', 'Ala'), ('pivot', 'Pívot'), ('universal', 'Universal')], max_length=20)),
                ('foto_url', models.TextField(blank=True)),
                ('informe_scout', models.TextField(blank=True)),
                ('identificador_federacion', models.CharField(blank=True, help_text='ID del jugador en federación / scraping', max_length=100, null=True, unique=True)),
                ('edad_estimacion', models.IntegerField(blank=True, help_text='Edad conocida/scrapeada si no tenemos fecha_nacimiento exacta.', null=True)),
                ('edad_estimacion_base_year', models.IntegerField(blank=True, help_text='Año natural en el que se obtuvo la edad_estimacion desde federación.', null=True)),
                ('edad_estimacion_bloqueada', models.BooleanField(default=False, help_text='Si True, NO autoincrementar edad_estimacion en enero.')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialJugadorScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_texto', models.CharField(blank=True, max_length=50)),
                ('competicion_texto', models.CharField(blank=True, max_length=200)),
                ('equipo_texto', models.CharField(blank=True, max_length=200)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_scraped', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Historial bruto de jugador (scraping)',
                'verbose_name_plural': 'Historial bruto de jugador (scraping)',
            },
        ),
        migrations.CreateModel(
            name='JugadorEnClubTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.CharField(blank=True, max_length=10)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('tarjetas_amarillas', models.IntegerField(default=0)),
                ('tarjetas_rojas', models.IntegerField(default=0)),
                ('convocados', models.IntegerField(default=0)),
                ('titular', models.IntegerField(default=0)),
                ('suplente', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_temporada', to='clubes.club')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_temporada', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_temporada', to='nucleo.temporada')),
            ],
            options={
                'unique_together': {('jugador', 'club', 'temporada')},
            },
        ),
    ]
