# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(help_text="Identificador de la fuente de datos (ej: 'scrape_semana')", max_length=100, unique=True)),
                ('last_success', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento de la última actualización correcta.')),
                ('detalle', models.TextField(blank=True, help_text='Resumen breve de lo que se actualizó.')),
            ],
            options={
                'verbose_name': 'Estado de sincronización de datos',
                'verbose_name_plural': 'Estados de sincronización de datos',
                'ordering': ['-last_success'],
            },
        ),
    ]
