# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pabellon', 'Pabellón'), ('equipo', 'Equipo'), ('escudo', 'Escudo'), ('otro', 'Otro')], default='otro', max_length=24)),
                ('titulo', models.CharField(blank=True, default='', max_length=140)),
                ('url', models.CharField(max_length=400)),
                ('visible_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('texto', models.TextField(blank=True, default='')),
                ('enlace', models.URLField(blank=True, default='', max_length=400)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubSeasonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competicion', models.CharField(max_length=140)),
                ('grupo_text', models.CharField(blank=True, default='', max_length=140)),
                ('pos_final', models.PositiveIntegerField(blank=True, null=True)),
                ('pj', models.PositiveIntegerField(default=0)),
                ('v', models.PositiveIntegerField(default=0)),
                ('e', models.PositiveIntegerField(default=0)),
                ('d', models.PositiveIntegerField(default=0)),
                ('gf', models.PositiveIntegerField(default=0)),
                ('gc', models.PositiveIntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-temporada__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClubSeasonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('puntos_acum', models.IntegerField(default=0)),
                ('gf_acum', models.IntegerField(default=0)),
                ('gc_acum', models.IntegerField(default=0)),
                ('pos_clasif', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grupo', 'jornada'],
            },
        ),
        migrations.CreateModel(
            name='ClubStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('rol', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('visible_publico', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['temporada__nombre', 'orden', 'rol', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClubTravelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_km', models.FloatField(default=0.0)),
                ('avg_km', models.FloatField(default=0.0)),
                ('max_km', models.FloatField(default=0.0)),
                ('min_km', models.FloatField(default=0.0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.FloatField(default=0.0)),
                ('duracion_min', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=160)),
                ('nombre_corto', models.CharField(blank=True, default='', max_length=80)),
                ('siglas', models.CharField(blank=True, default='', max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=180, null=True)),
                ('escudo_url', models.CharField(blank=True, default='', max_length=300)),
                ('color_primario', models.CharField(blank=True, default='', max_length=9)),
                ('color_secundario', models.CharField(blank=True, default='', max_length=9)),
                ('pabellon', models.CharField(blank=True, default='', max_length=160)),
                ('direccion', models.CharField(blank=True, default='', max_length=220)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('provincia', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('aforo_aprox', models.PositiveIntegerField(blank=True, null=True)),
                ('web', models.URLField(blank=True, default='', max_length=300)),
                ('email_contacto', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('twitter', models.URLField(blank=True, default='', max_length=300)),
                ('instagram', models.URLField(blank=True, default='', max_length=300)),
                ('facebook', models.URLField(blank=True, default='', max_length=300)),
                ('tiktok', models.URLField(blank=True, default='', max_length=300)),
                ('youtube', models.URLField(blank=True, default='', max_length=300)),
                ('fundado_en', models.PositiveIntegerField(blank=True, null=True)),
                ('historia_resumida', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='clubes_club_slug_a88f5b_idx'), models.Index(fields=['nombre_oficial'], name='clubes_club_nombre__bb49eb_idx'), models.Index(fields=['nombre_corto'], name='clubes_club_nombre__3020e8_idx'), models.Index(fields=['siglas'], name='clubes_club_siglas_532e4b_idx'), models.Index(fields=['ciudad', 'provincia'], name='clubes_club_ciudad_c9befd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('equipo_jornada', 'Equipo de la jornada'), ('partido_estrella', 'Partido estrella'), ('mvp_jornada', 'MVP de la jornada (club)')], max_length=32)),
                ('notas', models.CharField(blank=True, default='', max_length=240)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='clubes.club')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_club', to='nucleo.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ClubBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('cargo', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('visible_publico', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directiva', to='clubes.club')),
            ],
            options={
                'ordering': ['orden', 'cargo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClubEnGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('racha', models.CharField(blank=True, default='', max_length=10)),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visitante', models.IntegerField(default=0)),
                ('goles_favor_local', models.IntegerField(default=0)),
                ('goles_favor_visitante', models.IntegerField(default=0)),
                ('goles_contra_local', models.IntegerField(default=0)),
                ('goles_contra_visitante', models.IntegerField(default=0)),
                ('ult_5', models.CharField(blank=True, default='', max_length=5)),
                ('ult_10_puntos', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('goles_pp', models.IntegerField(default=0)),
                ('veces_equipo_de_la_jornada', models.PositiveIntegerField(default=0)),
                ('veces_partido_estrella', models.PositiveIntegerField(default=0)),
                ('veces_mvp_jornada', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='clubes.club')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='nucleo.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ClubManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar_identidad', models.BooleanField(default=True)),
                ('puede_editar_staff', models.BooleanField(default=True)),
                ('puede_editar_multimedia', models.BooleanField(default=True)),
                ('puede_editar_logistica', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='clubes.club')),
            ],
        ),
    ]
