# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmanager',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmedia',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubnota',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubnota',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_club', to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='clubseasonhistory',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubseasonhistory',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clubes', to='nucleo.temporada'),
        ),
        migrations.AddField(
            model_name='clubseasonprogress',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubseasonprogress',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_club', to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='clubstaffmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubstaffmember',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_clubes', to='nucleo.temporada'),
        ),
        migrations.AddField(
            model_name='clubtravelstat',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_stats', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubtravelstat',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_stats', to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='clubtravelstat',
            name='max_km_rival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubtravelstat',
            name='min_km_rival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubtravelstat',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_stats', to='nucleo.temporada'),
        ),
        migrations.AddField(
            model_name='clubtrip',
            name='club_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_recibiendo', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubtrip',
            name='club_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_saliendo', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='clubtrip',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='clubtrip',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.temporada'),
        ),
        migrations.AddIndex(
            model_name='clubaward',
            index=models.Index(fields=['grupo', 'tipo', 'jornada'], name='clubes_club_grupo_i_a2ff0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubaward',
            unique_together={('club', 'grupo', 'jornada', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='clubengrupo',
            index=models.Index(fields=['grupo', 'posicion_actual'], name='clubes_club_grupo_i_da7dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='clubengrupo',
            index=models.Index(fields=['grupo', 'puntos'], name='clubes_club_grupo_i_2915ff_idx'),
        ),
        migrations.AddIndex(
            model_name='clubengrupo',
            index=models.Index(fields=['grupo', 'diferencia_goles'], name='clubes_club_grupo_i_496f42_idx'),
        ),
        migrations.AddIndex(
            model_name='clubengrupo',
            index=models.Index(fields=['grupo', 'racha'], name='clubes_club_grupo_i_fed993_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubengrupo',
            unique_together={('club', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='clubmanager',
            unique_together={('club', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='clubmedia',
            index=models.Index(fields=['club', 'tipo'], name='clubes_club_club_id_1253d3_idx'),
        ),
        migrations.AddIndex(
            model_name='clubnota',
            index=models.Index(fields=['club', 'grupo'], name='clubes_club_club_id_d92bc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubseasonhistory',
            unique_together={('club', 'temporada', 'competicion', 'grupo_text')},
        ),
        migrations.AlterUniqueTogether(
            name='clubseasonprogress',
            unique_together={('club', 'grupo', 'jornada')},
        ),
        migrations.AlterUniqueTogether(
            name='clubstaffmember',
            unique_together={('club', 'temporada', 'nombre', 'rol')},
        ),
        migrations.AlterUniqueTogether(
            name='clubtravelstat',
            unique_together={('club', 'temporada', 'grupo')},
        ),
        migrations.AddIndex(
            model_name='clubtrip',
            index=models.Index(fields=['grupo', 'temporada'], name='clubes_club_grupo_i_9cd9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='clubtrip',
            index=models.Index(fields=['club_origen', 'grupo'], name='clubes_club_club_or_579fa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubtrip',
            unique_together={('club_origen', 'club_destino', 'temporada', 'grupo')},
        ),
    ]
