# Generated by Django 5.2.7 on 2025-11-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_tradicion', models.IntegerField(default=0)),
                ('cantera_talento', models.IntegerField(default=0)),
                ('intensidad_competitiva', models.IntegerField(default=0)),
                ('solidez_tactica', models.IntegerField(default=0)),
                ('proyecto_seriedad', models.IntegerField(default=0)),
                ('reputacion_respecto', models.IntegerField(default=0)),
                ('media_global', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='identificador_federacion',
            field=models.CharField(blank=True, help_text='ID del club en la federación (ej. 10176)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['identificador_federacion'], name='clubes_club_identif_6ff885_idx'),
        ),
        migrations.AddField(
            model_name='valoracionclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_club', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='valoracionclub',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_club', to='nucleo.temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracionclub',
            unique_together={('club', 'temporada')},
        ),
    ]
