# Generated by Django 5.2.7 on 2025-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_valoracionclub_club_identificador_federacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubboardmember',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubstaffmember',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
