# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaHistorialJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_texto', models.CharField(help_text="Texto libre tipo '2020/2021' por si esa temporada no está creada en BD", max_length=50)),
                ('goles_reportados', models.IntegerField(blank=True, null=True)),
                ('partidos_reportados', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_historial', to='clubes.club')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_historial', to='jugadores.jugador')),
            ],
        ),
    ]
