# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaFantasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jornada', models.IntegerField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta para elegir equipo'), ('cerrada', 'Cerrada / en juego'), ('finalizada', 'Finalizada')], default='abierta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PuntosFantasyJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('tarjetas', models.IntegerField(default=0)),
                ('mvp', models.BooleanField(default=False)),
                ('victoria_equipo', models.BooleanField(default=False)),
                ('puntos_resultado_final_calculado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFantasyUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales_semana', models.IntegerField(default=0)),
                ('posicion_en_ranking_semana', models.IntegerField(blank=True, null=True)),
                ('jugador_ala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_fantasy_ala', to='jugadores.jugador')),
                ('jugador_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_fantasy_cierre', to='jugadores.jugador')),
                ('jugador_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_fantasy_extra', to='jugadores.jugador')),
                ('jugador_pivot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_fantasy_pivot', to='jugadores.jugador')),
                ('jugador_portero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_fantasy_portero', to='jugadores.jugador')),
            ],
        ),
    ]
