# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantasy', '0001_initial'),
        ('jugadores', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipofantasyusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_fantasy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jornadafantasy',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_fantasy', to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='jornadafantasy',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_fantasy', to='nucleo.temporada'),
        ),
        migrations.AddField(
            model_name='equipofantasyusuario',
            name='jornada_fantasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_usuario', to='fantasy.jornadafantasy'),
        ),
        migrations.AddField(
            model_name='puntosfantasyjugador',
            name='jornada_fantasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_jugadores', to='fantasy.jornadafantasy'),
        ),
        migrations.AddField(
            model_name='puntosfantasyjugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_fantasy', to='jugadores.jugador'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadafantasy',
            unique_together={('grupo', 'temporada', 'numero_jornada')},
        ),
        migrations.AlterUniqueTogether(
            name='equipofantasyusuario',
            unique_together={('jornada_fantasy', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='puntosfantasyjugador',
            unique_together={('jornada_fantasy', 'jugador')},
        ),
    ]
