# Generated by Django 5.2.7 on 2025-11-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_alter_club_telefono_alter_clubboardmember_telefono_and_more'),
        ('fantasy', '0004_puntosmvptotaljugador'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosEquipoJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('puntos', models.FloatField(default=0.0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-temporada', '-jornada', '-puntos'],
            },
        ),
        migrations.CreateModel(
            name='PuntosEquipoTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_total', models.FloatField(default=0.0)),
                ('partidos_total', models.IntegerField(default=0)),
                ('victorias_total', models.IntegerField(default=0)),
                ('empates_total', models.IntegerField(default=0)),
                ('derrotas_total', models.IntegerField(default=0)),
                ('goles_favor_total', models.IntegerField(default=0)),
                ('goles_contra_total', models.IntegerField(default=0)),
                ('ultima_jornada_procesada', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-temporada', '-puntos_total'],
            },
        ),
        migrations.RenameIndex(
            model_name='puntosmvpjornada',
            new_name='fantasy_pun_jugador_725442_idx',
            old_name='fantasy_pun_jugador_7a8b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='puntosmvpjornada',
            new_name='fantasy_pun_tempora_144779_idx',
            old_name='fantasy_pun_tempora_8c9d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='puntosmvpjornada',
            new_name='fantasy_pun_tempora_c8223d_idx',
            old_name='fantasy_pun_tempora_9d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='puntosmvptotaljugador',
            new_name='fantasy_pun_tempora_836d6c_idx',
            old_name='fantasy_pun_tempora_ranking_idx',
        ),
        migrations.RenameIndex(
            model_name='puntosmvptotaljugador',
            new_name='fantasy_pun_jugador_d184a9_idx',
            old_name='fantasy_pun_jugador_temp_idx',
        ),
        migrations.AddField(
            model_name='puntosequipojornada',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_equipo_jornada', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='puntosequipojornada',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_equipo_jornada', to='nucleo.grupo'),
        ),
        migrations.AddField(
            model_name='puntosequipojornada',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_equipo_jornada', to='nucleo.temporada'),
        ),
        migrations.AddField(
            model_name='puntosequipototal',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_equipo_total', to='clubes.club'),
        ),
        migrations.AddField(
            model_name='puntosequipototal',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_equipo_total', to='nucleo.temporada'),
        ),
        migrations.AddIndex(
            model_name='puntosequipojornada',
            index=models.Index(fields=['club', 'temporada'], name='fantasy_pun_club_id_adac8d_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosequipojornada',
            index=models.Index(fields=['temporada', 'grupo', 'jornada'], name='fantasy_pun_tempora_d87adf_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosequipojornada',
            index=models.Index(fields=['temporada', 'jornada'], name='fantasy_pun_tempora_818af3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puntosequipojornada',
            unique_together={('club', 'temporada', 'grupo', 'jornada')},
        ),
        migrations.AddIndex(
            model_name='puntosequipototal',
            index=models.Index(fields=['temporada', '-puntos_total'], name='fantasy_pun_tempora_924add_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosequipototal',
            index=models.Index(fields=['club', 'temporada'], name='fantasy_pun_club_id_414f48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puntosequipototal',
            unique_together={('club', 'temporada')},
        ),
    ]
