# Generated by Django 5.2.7 on 2025-11-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_alter_club_telefono_alter_clubboardmember_telefono_and_more'),
        ('fantasy', '0005_puntos_equipo'),
        ('jugadores', '0002_add_slug_to_jugador'),
        ('nucleo', '0001_initial'),
        ('partidos', '0003_partido_score_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoleadorJornadaDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores_jornadas', to='nucleo.grupo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleador_jornadas_division', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores_jornadas_division', to='nucleo.temporada')),
            ],
            options={
                'indexes': [models.Index(fields=['jugador', '-fecha_creacion'], name='fantasy_gol_jugador_a280d2_idx'), models.Index(fields=['temporada', 'grupo', 'jornada'], name='fantasy_gol_tempora_db09d3_idx')],
                'unique_together': {('temporada', 'grupo', 'jornada')},
            },
        ),
        migrations.CreateModel(
            name='MejorEquipoJornadaDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('puntos', models.FloatField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejor_equipo_jornadas_division', to='clubes.club')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejores_equipos_jornadas', to='nucleo.grupo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejores_equipos_jornadas_division', to='nucleo.temporada')),
            ],
            options={
                'indexes': [models.Index(fields=['club', '-fecha_creacion'], name='fantasy_mej_club_id_0aba87_idx'), models.Index(fields=['temporada', 'grupo', 'jornada'], name='fantasy_mej_tempora_183055_idx')],
                'unique_together': {('temporada', 'grupo', 'jornada')},
            },
        ),
        migrations.CreateModel(
            name='MejorEquipoJornadaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField()),
                ('puntos', models.FloatField()),
                ('puntos_base', models.FloatField()),
                ('coef_division', models.FloatField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejor_equipo_jornadas_global', to='clubes.club')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejores_equipos_jornadas_globales', to='nucleo.grupo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mejores_equipos_jornadas_global', to='nucleo.temporada')),
            ],
            options={
                'indexes': [models.Index(fields=['club', '-fecha_creacion'], name='fantasy_mej_club_id_f59efc_idx'), models.Index(fields=['temporada', 'semana'], name='fantasy_mej_tempora_7374ce_idx')],
                'unique_together': {('temporada', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='MVPJornadaDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('puntos', models.FloatField()),
                ('puntos_con_coef', models.FloatField()),
                ('coef_division', models.FloatField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas', to='nucleo.grupo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas_division', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas_division', to='nucleo.temporada')),
            ],
            options={
                'indexes': [models.Index(fields=['jugador', '-fecha_creacion'], name='fantasy_mvp_jugador_5abdda_idx'), models.Index(fields=['temporada', 'grupo', 'jornada'], name='fantasy_mvp_tempora_2b36ee_idx')],
                'unique_together': {('temporada', 'grupo', 'jornada')},
            },
        ),
        migrations.CreateModel(
            name='MVPJornadaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField()),
                ('puntos', models.FloatField()),
                ('puntos_base', models.FloatField()),
                ('coef_division', models.FloatField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas_globales', to='nucleo.grupo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas_global', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_jornadas_global', to='nucleo.temporada')),
            ],
            options={
                'indexes': [models.Index(fields=['jugador', '-fecha_creacion'], name='fantasy_mvp_jugador_a8a333_idx'), models.Index(fields=['temporada', 'semana'], name='fantasy_mvp_tempora_b1232c_idx')],
                'unique_together': {('temporada', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='MVPPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.FloatField()),
                ('goles', models.IntegerField(default=0)),
                ('tarjetas_amarillas', models.IntegerField(default=0)),
                ('tarjetas_rojas', models.IntegerField(default=0)),
                ('mvp_evento', models.BooleanField(default=False)),
                ('equipo_ganador', models.BooleanField(default=False)),
                ('puntos_mvp_acumulados', models.FloatField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_partidos', to='jugadores.jugador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_partido', to='partidos.partido')),
            ],
            options={
                'indexes': [models.Index(fields=['jugador', '-fecha_creacion'], name='fantasy_mvp_jugador_326759_idx'), models.Index(fields=['partido'], name='fantasy_mvp_partido_b824cb_idx')],
            },
        ),
    ]
