# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('jugadores', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_numero', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('identificador_federacion', models.CharField(blank=True, help_text='ID del partido en federación (ej. 26318901)', max_length=50, unique=True)),
                ('pabellon', models.CharField(blank=True, max_length=200)),
                ('arbitros', models.TextField(blank=True)),
                ('indice_intensidad', models.IntegerField(blank=True, help_text='0-100: partido caliente/loco (muchos goles, muchas tarjetas...)', null=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='nucleo.grupo')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_local', to='clubes.club')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_visitante', to='clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('gol', 'Gol'), ('gol_pp', 'Gol en propia puerta'), ('amarilla', 'Tarjeta amarilla'), ('doble_amarilla', 'Doble amarilla'), ('roja', 'Tarjeta roja'), ('mvp', 'MVP del partido')], max_length=20)),
                ('nota', models.TextField(blank=True, help_text="Descripción rápida: 'Gol segundo palo en transición 3v2'")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_en_partidos', to='clubes.club')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_en_partidos', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='partidos.partido')),
            ],
        ),
        migrations.CreateModel(
            name='AlineacionPartidoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.CharField(blank=True, max_length=10)),
                ('titular', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, help_text='Pt=portero, Ps=portero suplente, C=capitán, etc.', max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_partido', to='clubes.club')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones_en_partidos', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_jugadores', to='partidos.partido')),
            ],
        ),
    ]
