# Generated by Django 5.2.7 on 2025-11-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='identificador_federacion',
            field=models.CharField(blank=True, help_text='ID del partido en federación (ej. 26318901)', max_length=50, null=True, unique=True),
        ),
    ]
