# Generated by Django 5.2.7 on 2025-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_alter_partido_identificador_federacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='score_interes',
            field=models.FloatField(blank=True, help_text='Score de interés del partido calculado en función de clasificación, racha, goles, etc. Se calcula una vez y no cambia.', null=True),
        ),
    ]
