# Generated by Django 5.2.7 on 2025-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_texto', models.CharField(max_length=20, unique=True)),
                ('jornada_actual', models.IntegerField(default=1)),
                ('jornada_pendiente_minima', models.IntegerField(default=1)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
