# Generated by Django 5.2.7 on 2025-11-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoscraping',
            name='status',
            field=models.CharField(db_index=True, default='ok', max_length=20),
        ),
    ]
