# Generated by Django 5.2.7 on 2025-11-30 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0004_alter_club_telefono_alter_clubboardmember_telefono_and_more'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('partidos_jugados_total', models.PositiveIntegerField(default=0, help_text='Total de partidos jugados hasta esa jornada')),
                ('equipos_participantes', models.PositiveIntegerField(default=0, help_text='Número de equipos en la clasificación')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_jornada', to='nucleo.grupo')),
            ],
            options={
                'verbose_name': 'Clasificación por Jornada',
                'verbose_name_plural': 'Clasificaciones por Jornada',
                'ordering': ['grupo', 'jornada'],
            },
        ),
        migrations.CreateModel(
            name='PosicionJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(help_text='Posición en la clasificación (1, 2, 3...)')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('racha', models.CharField(blank=True, default='', help_text="Últimos 5 resultados: 'VVEDV' (Victoria, Victoria, Empate, Derrota, Victoria)", max_length=10)),
                ('enfrentamientos_directos', models.JSONField(blank=True, help_text='Datos de enfrentamientos directos para desempate', null=True)),
                ('clasificacion_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='clasificaciones.clasificacionjornada')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_jornada', to='clubes.club')),
            ],
            options={
                'verbose_name': 'Posición por Jornada',
                'verbose_name_plural': 'Posiciones por Jornada',
                'ordering': ['clasificacion_jornada', 'posicion'],
            },
        ),
        migrations.AddIndex(
            model_name='clasificacionjornada',
            index=models.Index(fields=['grupo', 'jornada'], name='clasificaci_grupo_i_abe18f_idx'),
        ),
        migrations.AddIndex(
            model_name='clasificacionjornada',
            index=models.Index(fields=['grupo', '-jornada'], name='clasificaci_grupo_i_50a59e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionjornada',
            unique_together={('grupo', 'jornada')},
        ),
        migrations.AddIndex(
            model_name='posicionjornada',
            index=models.Index(fields=['clasificacion_jornada', 'posicion'], name='clasificaci_clasifi_7cd03e_idx'),
        ),
        migrations.AddIndex(
            model_name='posicionjornada',
            index=models.Index(fields=['club', 'clasificacion_jornada'], name='clasificaci_club_id_5ad3f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posicionjornada',
            unique_together={('clasificacion_jornada', 'club')},
        ),
    ]
