# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('nucleo', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_temporada', to='clubes.club')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_tecnicos', to='nucleo.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEnPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_en_partidos', to='clubes.club')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_partido', to='partidos.partido')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apariciones_en_partidos', to='staff.staffclub')),
            ],
        ),
    ]
