# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('jugadores', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distintivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_aplicable', models.CharField(choices=[('jugador', 'Jugador'), ('club', 'Club'), ('usuario_manager', 'Usuario / Manager Fantasy')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DistintivoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField(blank=True, help_text='Jornada concreta si aplica (Jugador de la Jornada 7, etc.)', null=True)),
                ('comentario_publico', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distintivos', to='clubes.club')),
                ('distintivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='destacados.distintivo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distintivos', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distintivos_asignados', to='nucleo.temporada')),
            ],
        ),
    ]
