# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        ('jugadores', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoValoracionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('peso_aplicado', models.IntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_valoracion', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_valoracion', to='nucleo.temporada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoeficienteClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_referencia', models.IntegerField(blank=True, help_text='Jornada sobre la que se calculó este coeficiente.', null=True)),
                ('valor', models.FloatField(default=1.0)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_temporada', to='clubes.club')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_clubes', to='nucleo.temporada')),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'unique_together': {('club', 'temporada', 'jornada_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ValoracionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('pase', models.IntegerField(default=0)),
                ('regate', models.IntegerField(default=0)),
                ('potencia', models.IntegerField(default=0)),
                ('intensidad', models.IntegerField(default=0)),
                ('vision', models.IntegerField(default=0)),
                ('regularidad', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('media_global', models.FloatField(default=0.0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='jugadores.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_jugadores', to='nucleo.temporada')),
            ],
            options={
                'unique_together': {('jugador', 'temporada')},
            },
        ),
    ]
