# Generated by Django 5.2.7 on 2025-11-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeficienteDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_referencia', models.IntegerField(blank=True, help_text='Jornada sobre la que se calculó este coeficiente (opcional).', null=True)),
                ('valor', models.FloatField(default=1.0)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_division', to='nucleo.competicion')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_division', to='nucleo.temporada')),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'unique_together': {('competicion', 'temporada', 'jornada_referencia')},
            },
        ),
    ]
