# Generated by Django 5.2.7 on 2025-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrajePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, help_text='Principal / Auxiliar / Mesa / Cronometrador...', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificador_federacion', models.CharField(blank=True, help_text='ID oficial del árbitro en la federación (si lo tenemos)', max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
