# Generated by Django 5.2.7 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbitros', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrajepartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrajes', to='partidos.partido'),
        ),
        migrations.AddField(
            model_name='arbitrajepartido',
            name='arbitro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_dirigidos', to='arbitros.arbitro'),
        ),
    ]
